### ISSUE TITLE
[2.x] Tenant Domain model identifier

### ISSUE THREAD

**Issue by antonkomarev** [archtechx/tenancy#140]
Domain model doesn't have identifier, so how users will edit those records?

```php
$domain = Domain::where('domain', 'test.example.com')->first();
```

If column `domain` is an identifier - how will it be represented in API?

```js
{
    "type": "Domain",
    "id": "test.example.com"
    "attributes": {
        "domain": "test.example.com
    }
}
```

**Comment by stancl** [comment]
This is a bug, then: https://github.com/stancl/tenancy/blob/d00cf97e0ee0433afae3a627c03163fe45cefc22/src/StorageDrivers/Database/DomainModel.php#L17

Since in the migration, `domain` is unique, `domain` should be the identifier, and should be changed to a primary key.

https://github.com/stancl/tenancy/blob/d00cf97e0ee0433afae3a627c03163fe45cefc22/assets/migrations/2019_09_15_000020_create_domains_table.php#L20

**Comment by antonkomarev** [comment]
Why don't you want to add `id` column?

**Comment by stancl** [comment]
What would be the benefit of that?

**Comment by antonkomarev** [comment]
I look on it in perspective of API resource development. I just never using resource attributes as identifier because attribute value could be changed over time, but `id` should be immutable. It will work that way if there is no way to update `domain` column, only delete and create a new resource if you need to make a change.

I'm not against of current implementation. Just want to know the motivation.
Since domain doesn't have port it's allowed to be used in URI because `.` is a safe character, but if you will add support of `domain:port` - then it will became a problem because `:` is a reserved character:
`GET /domains/test.example.com` (good)
`GET /domains/test.example.com:8000` will be transformed to:
`GET /domains/test.example.com%3A8000` (bad)

**Comment by stancl** [comment]
I see.

> Just want to know the motivation.

I'm generally not a fan of adding `id` fields when other primary keys can be used.

Regarding your example, I see your point, but:
- I don't think I'll want to add port support. I don't see why someone would use that when they can use subdomains
- `GET /domains/test.example.com` is much nicer than `GET /domains/56` :smile: (imo)
- If you would *really* need the `id` because of some functionality specific to your app, you can make a new storage driver. (This made me think about a way to configure the models used by the DB storage driver, but I'm not sure that's a good idea, because the DB storage driver depends on specific behavior of the models.)

**Comment by stancl** [comment]
I'll keep this open because of: https://github.com/stancl/tenancy/issues/140#issuecomment-535542121

The migration & model should be fixed.

**Comment by antonkomarev** [comment]
I see issue with model, but whats wrong with the migration?

**Comment by stancl** [comment]
Should be `primary()`, not just `unique()`. I guess changing the model would make for example `find()` work with the domain, but I want to have a primary key on the DB level.

**Comment by antonkomarev** [comment]
If it will be primary - then it doesn't need to be unique because primary keys are unique by definition.

**Comment by stancl** [comment]
Yeah, I meant replacing `unique()` with `primary()`.
