### ISSUE TITLE
Telescope cause blank page.

### ISSUE THREAD

**Issue by hakanersu** [archtechx/tenancy#152]
#### Describe the bug
When i create fresh installation with telescope and create a tenant. Tenant page returns blank page. When i comment line below it works just as expected.
 
https://github.com/stancl/tenancy/blob/bde103560977cd399553c7dc862f838ef619dadb/src/Features/TelescopeTags.php#L35

#### Steps to reproduce
* Create a fresh laravel with db connection.
* Install laravel/telescope and migrate.
* Create a tenant in tinker with command below
```
Tenant::new()->withDomains(['tenant1.example.test'])->withData(['plan' => 'free'])->save();
```
* Try to access setted tenant. (tenant1.example.test) 

#### Expected behavior
Returns tenant with default tenant route view like below
```
This is your multi-tenant application. The id of the current tenant is 51c5c250-e399-11e9-9f81-3775b95e72e5
```

#### Your setup
 - Laravel version 6.0.4
 - stancl/tenancy version 2.x-dev (head 6cb7f27)
 - Storage driver Redis

**Comment by stancl** [comment]
I can reproduce this. Seems like the Telescope callback is executed before the tenant is identified.

**Comment by stancl** [comment]
@hakanersu 

Can you test if https://github.com/stancl/tenancy/commit/102ade4d8c61c5592a5df311d59ecca584a83c17 fixed it for you?

Apparently, the callback is called multiple times, even before tenancy is initialized, despite the middleware priority. Surreal, but making the helper return null instead of throwing an exception fixes this. :man_shrugging: 

![Screenshot from 2019-09-30 19-47-13](https://user-images.githubusercontent.com/33033094/65902643-3212e780-e3bb-11e9-9225-7ee66e1ae00a.png)

**Comment by hakanersu** [comment]
@stancl Yes its fixed thank you. :tada:
