### ISSUE TITLE
Laravel 5 compatibility

### ISSUE THREAD

**Issue by moazam1** [archtechx/tenancy#185]
We are using Laravel 5.8 in our project and we are not ready to switch to Laravel 6. Any chance you can make your package compatible with Laravel 5.8 and onwards?

` Problem 1
    - Conclusion: remove laravel/framework v5.8.35
    - Conclusion: don't install laravel/framework v5.8.35
    - stancl/tenancy 2.x-dev requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0].
    - stancl/tenancy v2.1.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.1.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.2.0|don't install laravel/framework v5.8.35
    - don't install illuminate/support v6.3.0|don't install laravel/framework v5.8.35
    - Installation request for laravel/framework (locked at v5.8.35, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.35].
    - Installation request for stancl/tenancy ^2.1 -> satisfiable by stancl/tenancy[2.x-dev, v2.1.0].`

**Comment by drbyte** [comment]
I can't speak for @stancl but I notice in https://github.com/stancl/tenancy/issues/123 that it appears it was intentional to drop Laravel 5 support in the v2.0 branch while taking the opportunity to break backward compatibility in order to accomplish the goals of v2.

v1 will work with Laravel 6, but the configs and docs and internal methodology are different and it'll be harder to get support for older versions.

**Comment by stancl** [comment]
@drbyte is right:

> it was intentional to drop Laravel 5 support in the v2.0 branch while taking the opportunity to break backward compatibility in order to accomplish the goals of v2.

I think that v2 doesn't depend on any 6.x-specific features, but I'm a bit hesitant to add 5.8 support.

- I don't want to be stuck in 5.8 feature set. If I added 5.8 support, I'd reserve the right to remove it at any time without making a new major release and without porting future bugfixes to some branch for 5.8.
- The CI takes like 5 minutes to run the tests already, not sure I want to increase this to 10 minutes.

@moazam1 
> we are not ready to switch to Laravel 6

Why exactly? Because of your dependencies? I suggest asking them to add L6 support instead of asking other packages to add support for a dead Laravel version.

L6 is an LTS version, so everyone should be motivated to upgrade. I'll think about if I want to add L5 support, but currently I'm leaning to the side of "no". It's just not worth the additional complexity for me, to support a few apps that haven't upgraded to L6 yet.

**Comment by stancl** [comment]
Yeah, I won't be adding this. L5.8 is unsupported for almost 2 months now and L6 is an LTS release.

**Comment by moazam1** [comment]
Thanks @stancl we are dependent on other libraries. I decided to write code by myself for multi-tenancy part.
