### ISSUE TITLE
Api only

### ISSUE THREAD

**Issue by JapSeyz** [archtechx/tenancy#196]
#### Description
Hi, this may be an edge case, so take it with a grain of salt. 

I am working on an api-only application that uses multi tenancy, and currently there's a few hiccups with that.

1) the forced "Web" middleware on the tenants.php routes. This was solved by moving the routes to api.php and adding the tenancy middleware in the RouteServiceProvider, but it would be nice to have the option to have the routes in tenant.php.

2) is it possible to have storage_path return the path without a tenant id? The issue is when you deploy with Vapor and laravel passport generates a key pr. Tenant, as that key won't be on all of the cloud containers, so we need to ship one key file with the application that'll be the same for a containers. 

3) is it possible to identify the tenant via a query parameter or a header for example? Instead of only via the host 

#### Why this should be added
It's great for API only platforms, but I don't know how popular they are. 

Thanks for the stellar work! 

Cheers

**Comment by stancl** [comment]
> This was solved by moving the routes to api.php and adding the tenancy middleware in the RouteServiceProvider, but it would be nice to have the option to have the routes in tenant.php.

I was going to say that this is not a workaround, that it's the right way to create tenant routes per the docs: https://tenancy.samuelstancl.me/docs/v2/tenant-routes/#custom-groups

But perhaps it could be cleaner to have a default `routes/tenant.php` file with a structure like this:

```php
Route::middleware('web')->group(function () {
    Route::get('/app', function () { ... });
});

Route::middleware('api')->prefix('api')->group(function () {
    //
});
```

I don't see a way to implement this in 2.0 without causing breaking changes though. Maybe it's something we can do in 3.0. For now, if you want a separate file for tenant API routes, you can create it and register it in your `RouteServiceProvider`.

> is it possible to identify the tenant via a query parameter or a header for example? Instead of only via the host

Sure. You could do something like this:

```php
use Tenancy;

Route::get('/api/{tenant}/users', function ($tenant) {
    Tenancy::initialize(Tenancy::find($tenant));

    return User::all();
});
```

Should work with no issues. (Of course, you don't have to use closure routes, I'm just making the example simple.)

> is it possible to have storage_path return the path without a tenant id

Could you contact me on [Telegram](https://t.me/samuelstancl) or Discord (I'm `Samuel Štancl#4783` on the official Laravel Discord)? I don't have any experience with Vapor or Passport so I'd love to talk to someone who does, so that I can get some insight into what I can make easier.
