### ISSUE TITLE
TenantAware Commands

### ISSUE THREAD

**Issue by viezel** [archtechx/tenancy#218]
#### Description
Often when running a SaaS, we need to run tenant specific commands. Having a trait or BaseCommand to extent - or even magical automatic setup. 

#### Why this should be added
I know you have the `tenancy()->all($this->option('tenants'))->each(...)` syntax in place, but I will suggest to have a forced command with only one tenant. do to the fact that if you forget the argument, then it runs the command on all tenants - which can lead to incorrect operations.

I suggest

```php
tenancy()->only($this->option('tenant'))->run(function ($tenant) {
    // call the command 
});
```

and a new `HasATenantOption` that is required. 

```php
trait HasATenantOption
{
    protected function getOptions()
    {
        return array_merge([
            ['tenant', null, InputOption::VALUE_REQUIRED, '', null],
        ], parent::getOptions());
    }
}
```

I can do a PR, but still a bit new to the project in terms of how to do those magical setups. so I will let you decide how to proceed.

**Comment by stancl** [comment]
You can use `tenants:run` to run a command for specific tenant(s). But I've also been thinking about a `TenantAware` trait. I'll explore the idea a bit more.

**Comment by stancl** [comment]
I'll add a `TenantAwareCommand` trait but I disagree with this:
> do to the fact that if you forget the argument, then it runs the command on all tenants - which can lead to incorrect operations.

I don't like the idea of removing features because users could make a mistake. It should be the user's responsibility to implement `confirmToProceed()` on dangerous commands.

Anyway, I decided to go with `abstract protected function getTenants(): array` on the `TenantAwareCommand`, so that you can return an array with a single tenant if it doesn't make sense to execute some command on multiple tenants.
