### ISSUE TITLE
Suport for XML Api for CPanel

### ISSUE THREAD

**Issue by themodernpk** [archtechx/tenancy#234]
Hello Guys,

Cpanel does not allow to create mysql database using `mysql_query`, is there any way to workaround?

**Comment by stancl** [comment]
Can you give more details?

**Comment by themodernpk** [comment]
@stancl Cpanel does not allow to run `CREATE DATABASE newdatabase`, in my case when I try to create tenant using your package it create following error:
```
SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user '***'@'localhost' to database 'tenant3209b0f5-76dd-4de1-8ee4-381cad014c88' (SQL: CREATE DATABASE `tenant3209b0f5-76dd-4de1-8ee4-381cad014c88` CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`)
```
This is because Cpanel does not allow to run certain `mysql_query` instead it offer `api` do to that https://github.com/CpanelInc/xmlapi-php 

So, that's my situation. Any idea how to handle such scenarios?

**Comment by stancl** [comment]
Sure. This file is what's responsible for creating the tenant databases:

https://github.com/stancl/tenancy/blob/fd00be646e82f07cae0a36c7e76c17310c50779a/src/TenantDatabaseManagers/MySQLDatabaseManager.php#L21-L27

Write your own `TenantDatabaseManager` that's similar to this one, but use the Cpanel API instead of DB statements to create the database.

Then configure that class as the database manager for `mysql` databases:

https://github.com/stancl/tenancy/blob/fd00be646e82f07cae0a36c7e76c17310c50779a/assets/config.php#L58-L63
