### ISSUE TITLE
Support for Multischema for PostgreSQL

### ISSUE THREAD

**Issue by nuradiyana** [archtechx/tenancy#235]
Hi, in PostgreSQL, we can create many schema in one database, this is will be great if this package support this feature. Is there any support for this?

**Comment by stancl** [comment]
Hi. I'm not sure if this is the better solution (https://stackoverflow.com/questions/1152405/postgresql-is-it-better-to-use-multiple-databases-with-one-schema-each-or-one#comment29252609_1157008) as I don't have much experience with Postgres, but I think adding this feature shouldn't be very hard.

You'd need a `TenantDatabaseManager` [like this one](https://github.com/stancl/tenancy/blob/2.x/src/TenantDatabaseManagers/PostgreSQLDatabaseManager.php) that would create & delete schemas instead of databases.

And then the `DatabaseManager` would have to be slightly changed to switch the (presumably) `schema` config key, instead of the `database` key:
https://github.com/stancl/tenancy/blob/fd00be646e82f07cae0a36c7e76c17310c50779a/src/DatabaseManager.php#L103

I'll see if I can make this happen in 2.3.0.

**Comment by viezel** [comment]
@NoorAdiana sounds cool, but out of curiosity - is it performant with multiple schemas?

**Comment by iskrisis** [comment]
@viezel as far as i know Mysql has no equivalent to "postgres database". Postgres database is the whole mysql namespace. Meaning postgres schema is equivalent to mysql database. In postgres making database per tenant is probably slower and it would make more sense have schema per tenant.

**Comment by stancl** [comment]
Resolved in https://github.com/stancl/tenancy/pull/237
