### ISSUE TITLE
Namespacing Tenant Models

### ISSUE THREAD

**Issue by richeklein** [archtechx/tenancy#238]
Is it a common practice to maintain separate namespaces for central and tenant models? For example: `App\Models` and `App\Tenant\Models`. Are there any drawbacks to using this structure with the tenancy package? Thanks.

**Comment by stancl** [comment]
I personally recommend it. Since the database switch happens automatically in the background, it's a good idea to separate models, controllers, etc into Central/Tenant directories.

In a project I'm working on right now, this is how I structure my controllers:

![Screenshot from 2019-12-01 22-09-31](https://user-images.githubusercontent.com/33033094/69920355-4fc9ff00-1487-11ea-9d80-bd6500ae6a41.png)

I use the the Auth controllers & their routes in both the central and the tenant part of the app, so they're outside the `Tenant`/`Central` directories. Everything else is nicely categorized.

**Comment by richeklein** [comment]
Thanks for the tip! If your Tenant databases have separate users does it make sense to have separate models Models/Tenant/User and Models/Central/User? I'm thinking I could get away with managing the relationships for both the central and tenant users in one model since database switching is automatic.

**Comment by stancl** [comment]
If the model is identical then just use the same model. If the *User* object represents different things in different parts of the app, use two models.

**Comment by richeklein** [comment]
Do you have a donation link?

**Comment by stancl** [comment]
I do :)

https://gumroad.com/l/tenancy

**Comment by stancl** [comment]
@neovive Thank you.

**Comment by richeklein** [comment]
Thank you so much for creating and supporting such a great library!
