### ISSUE TITLE
Syntax Error Json Unquote

### ISSUE THREAD

**Issue by patboyrico** [archtechx/tenancy#239]
I don't know if this is a package issue or a laravel issue but here is the issue i am facing. $table->json is giving me an error in my mariadb so i decided to make the use of a text field. Now tenancy()->findBy gives the following error
`FUNCTION database.json_unquote does not exist` . What is the workaround for this? Thanks in advance. Best multi tenant app by miles.

**Comment by stancl** [comment]
Right, the issue is that to find a tenant by something in the JSON strings with the tenants' data, the database needs to query the JSON field.

This is the code:

https://github.com/stancl/tenancy/blob/a8f84d280860e003ca00a8e67ce78ec8962bbd24/src/StorageDrivers/Database/TenantRepository.php#L35-L42

`->` is used to query nested JSON strings.

You can solve this by creating a column on the `tenants` table for the key by which you find tenants and adding that field to the `tenancy.storage_drivers.db.custom_columns` config.

**Comment by patboyrico** [comment]
It

**Comment by patboyrico** [comment]
THank you it solved my issue. Thumbs up
