### ISSUE TITLE
Backpack implementation

### ISSUE THREAD

**Issue by t-prod** [archtechx/tenancy#245]
Hi,

I try to implement backpack with your fantastic tenancy package. I think there's a middleware to allow with "tenancy". How can I do to allow backpack to be executed on each tenants ?

Thanks for your help,

Regards

**Comment by stancl** [comment]
Hi,

Hmm. Never used Backpack. Looks like the middleware for Backpack routes is hardcoded: https://github.com/Laravel-Backpack/Base/blob/master/src/routes/backpack/base.php#L16 https://github.com/Laravel-Backpack/Base/blob/master/src/routes/backpack/custom.php#L11

You want the routes to use the `tenancy` middleware.

**Comment by t-prod** [comment]
You're right it's hardcoded and the middleware tenancy must be added.

**Comment by mansourcodes** [comment]
I have the same feature request.

However, I found this solution but it seems missing something 

################

The [docs for that tenancy package](https://tenancyforlaravel.com/docs/v3/tenant-identification) show that they use a various middlewares that set the tenant for the application. Based on your question, Ill assume you're using the `Subdomain identification` middleware in your app.

The issue is most likely that your Backpack permissions routes are not using this middleware.


If we look at [Backpack's docs](https://github.com/Laravel-Backpack/PermissionManager), they say this about the permissions routes:

> If you need to modify how this works in a project:
>
>create a routes/backpack/permissionmanager.php file; the package will see that, and load your routes file, instead of the one in the package;


To fix the issue, create a file at `allin.com/routes/backpack/permissionmanager.php` copy the contents from `vendor/backpack/permissionmanager/src/routes/backpack/permissionmanager.php`, paste that in the new file and add the middleware needed for the tenancy app, which should look something like:


    Route::group([
        'namespace'  => 'Backpack\PermissionManager\app\Http\Controllers',
        'prefix'     => config('backpack.base.route_prefix', 'admin'),
        'middleware' => ['web', InitializeTenancyBySubdomain::class, backpack_middleware()],
    ], function () {
        Route::crud('permission', 'PermissionCrudController');
        Route::crud('role', 'RoleCrudController');
        Route::crud('user', 'UserCrudController');
    });

################

source: https://stackoverflow.com/questions/63011491/backpack-with-multi-tenancy

**Comment by martincarvalho** [comment]
Were you guys able to make this work?
