### ISSUE TITLE
Event "tenant.created" is triggered and tenant->persisted is still FALSE.

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#271]
#### Describe the bug
When creating a new tenant, the method `tenant->save()` will call `manager->createTenant()`, which will trigger the event "tenant.created" after it's done, but the `tenant->persisted` will be set to true _AFTER_ this event is triggered. Now if you call the new tenant within the "tenant.created" hook, you will find it not persisted!

#### Steps to reproduce
```php
tenancy()->hook('tenant.created', function($manager, $tenant){
dd($tenant->persisted) // === false
// Now try for example:
$tenant->put('created', true); // Wont be saved, since its not persisted!
});

Tenant::create(...);
```
#### Expected behavior
The tenant should be flagged as persisted before the "tenant.created" is triggered, since now it exists in the database.

#### Your setup
 - Laravel version: 6.11
 - stancl/tenancy version: 2.2.5
 - Storage driver: DB

**Comment by stancl** [comment]
Nice catch.

The `$this->persisted = true`:

https://github.com/stancl/tenancy/blob/5ebb68e860119b4508d86f2150d2dd7ce4696bd5/src/Tenant.php#L236

 should be done in the `TenantManager::createTenant()` method anyway, because

```php
$tenant = Tenant::new()->withData([...]);

$tenantManager->createTenant($tenant);
```

should also be supported, since it's a public method.

I'll tag a patch release shortly.
