### ISSUE TITLE
address the middleware required change when using Livewire

### ISSUE THREAD

**Issue by sergeByishimo** [archtechx/tenancy#344]
Hello sir!

when using the laravel livewire framework, it is required that you change the middleware group from the default `web` to `tenancy` in the package's config file. it took me a while to figure it out and thought it might help some people who are trying to use this package and livewire. thanks.

```
/*
    |--------------------------------------------------------------------------
    | Livewire Endpoint Middleware Group
    |--------------------------------------------------------------------------
    |
    | This value sets the middleware group that will be applied to the main
    | Livewire "message" endpoint (the endpoint that gets hit everytime,
    | a Livewire component updates). It is set to "web" by default.
    |
    */

    'middleware_group'  => 'tenancy',

```

**Comment by stancl** [comment]
Hi, thanks for sharing. Once I get to play with Livewire, I'll see exactly how this works and will add it to the docs.

**Comment by sergeByishimo** [comment]
ok no problem!

**Comment by stancl** [comment]
Actually, you want to use this:

```php
'middleware_group' => ['web', 'universal'],
```

which will let you use Livewire both in the tenant app and the central app. The web middleware should be kept there because it's there by default.

**Comment by sergeByishimo** [comment]
Aaahh.. i see! i haven't thought about it. 

but where does the `universal` middleware come from?

**Comment by stancl** [comment]
https://tenancy.samuelstancl.me/docs/v2/universal-routes/#universal-routes

Dne pá 10. dub 2020 18:19 uživatel Serge Byishimo <notifications@github.com>
napsal:

**Comment by sergeByishimo** [comment]
good to know! thanks for the update!

**Comment by stancl** [comment]
https://github.com/stancl/tenancy-docs/commit/24e63076da73addd7364e97edd124794d6d95f5a

**Comment by colinmackinlay** [comment]
but 'universal' middleware group isn't defined anywhere, certainly not in Kernel.php unless I've missed this in the setup instructions? I can't see what this change to config/livewire.php is achieving?
```
'middleware_group' => ['web', 'universal']
```

**Comment by stancl** [comment]
There's a `PreventAccessFromTenantDomains` middleware that prevents visiting central routes on tenant domains (& vice versa). You wouldn't want to see the landing page in the tenant's app.

The `universal` middleware group shortcircuits [1] that PreventAccess... middleware and lets any request pass, since it declares the route as universal [2] (= accessible on both central & tenant domains).

[1] https://github.com/stancl/tenancy/blob/7eb3395807c689a74ce4f6303afa93ce8c8ee25c/src/Middleware/PreventAccessFromTenantDomains.php#L25-L28

[2] https://tenancyforlaravel.com/docs/v2/universal-routes/#universal-routes
