### ISSUE TITLE
Helper for global context

### ISSUE THREAD

**Issue by obrunsmann** [archtechx/tenancy#487]
I suggest adding an helper to run some part of the code in global context. More or less an opposite to the `run()`-Method on tenant model.

**Example:**
```
global()->run(function() use($subscription) {
  $subscription('xx')->swap();
});
```

There are cases without access to the e.g. model so that I can't add the `CentralConnection` Trait to it. Specifically I have that problem with the _cashier-mollie_ package which does not yet provide a functionality to customize the models (https://github.com/laravel/cashier-mollie/issues/146).

I have to run the swap method in global context to work.

**Comment by christophheich** [comment]
Would be great to get such a global helper function.

**Comment by abhinay1435** [comment]
Hello, @stancl 
tenancy->central(function ($callback) {
User::all();
});
The Helper is great when we just need the full object of a table.

I tried to implement the following in my code and it was not working

$id = 1;
$admin_details= tenancy()->central(function ($id) {
                        return User::find($id);
            });

This returned null
what is the go through for this
to pass id or any other variable or an object in the central function instead of $tenant

**Comment by stancl** [comment]
Please don't spam the repo and follow the issue templates.

**Comment by abhinay1435** [comment]
Apologies
