### ISSUE TITLE
Add RunCentral method

### ISSUE THREAD

**Issue by GENL** [archtechx/tenancy#511]
#### Description
It could be very helpful to have a method to run a callback in the central context.

I imagine something like `tenancy()->runCentral($callback)`
It could be implemented by ending the current tenancy context(if any) and then after the callback is ran, re-initialize the tenancy with the closed tenant. I don't know if this approach comes with any side effects. But you have the idea

#### Why this should be added
This is very useful when needed to read/write a value in the central database when we are in the tenant context.

Maybe there is another way to meet my need, just let me know.

**Comment by stancl** [comment]
Hey.

Yeah, this is planned. See #487. I'll try to add this soon.

(Closing to only have 1 issue for this open)

**Comment by abhinay1435** [comment]
Hello, @stancl 
tenancy->central(function ($callback) {
User::all();
});
The Helper is great when we just need the full object of a table.

I tried to implement the following in my code and it was not working

$id = 1;
$admin_details= tenancy()->central(function ($id) {
                        return User::find($id);
            });

This returned null
what is the go through for this
to pass id or any other variable or an object in the central function instead of $tenant
