### ISSUE TITLE
Allow defining the tenant connection template using array syntax in config

### ISSUE THREAD

**Issue by stancl** [archtechx/tenancy#529]
#### Description

Allow defining the template connection using an array, like this:

```php
'template_tenant_connection' => [
    'driver' => 'mysql',
    // ...
],
```

And maybe (?) merge it with the central connection? Because if a completely custom connection was needed, we'd be using one created in the database config.

#### Why this should be added

To avoid having to create a template connection in `config/database.php`.

**Comment by lcdss** [comment]
This feature is or will be included in v4?

**Comment by stancl** [comment]
Yes

**Comment by viraljetani** [comment]
Is there an example of a working file where there are multiple connections to different database servers used for different tenants? 
I am really stuck when trying to create a tenant whose database I want to keep on a RDS server which is different from the central database server.

I have gone through the documentation https://tenancyforlaravel.com/docs/v3/customizing-databases/ 
Which has one paragraph specifying what to do but its not very clear from it where to define that: 

`To specify the connection that should be used to construct this tenant's database connection (the array like you'd find in config/database.php, set the tenancy_db_connection key. Otherwise, the connection whose name is in the tenancy.database.template_connection config will be used. If that key is null, the central connection will be used.`

I tried defining the tenancy_db_connection key into the tenancy.php config file under database and tried using a new connection from database.php but when creating a tenant it used the central database connection.

Any pointers would be appreciated. Thank you.

**Comment by masiorama** [comment]
I am trying to achieve the same as @viraljetani. Which is the right way to target a tenant connection?
In my case I am using multi database tenancy.
Thanks in advance!
