### ISSUE TITLE
Unable to UserImpersonate using JWT Guard

### ISSUE THREAD

**Issue by brandonellis** [archtechx/tenancy#584]
#### Describe the bug
The Code in UserImpersonation.php file on line 52  is being reported as 'Undefined Method'.  This blocks the ability to login using jwt.  I have tried other auth guards as well -> web, api with the same result.  My HTTP Requests are via SPA client utilizing JWT tokens.  The token generated by the impersonate() method is valid and visible in the database.

`Auth::guard($token->auth_guard)->loginUsingId($token->user_id); // loginUsingId() is an undefined method` 

#### Steps to reproduce
Attempt to authenticate with a valid token but received a 'Bad Method Exception' as loginUsingId() is not defined. 

#### Expected behavior
Be validated after submitting a valid user impersonation token

#### Your setup
 - Laravel version: [e.g. 8.22.1]
 - stancl/tenancy version: [e.g. 3.1.4]

**Comment by stancl** [comment]
`loginUsingId()` is supported by the default stateful auth.

So for custom auth guards, you'll need to make sure that they're compatible.

If you have a solution that works with all auth guards, I'm happy to merge a PR.

Though I'm not sure if `loginUsingId` even makes sense for JWT, because afaik JWT is stateless so this stateful impersonation logic can't be expected to work.

**Comment by brandonellis** [comment]
Ok, I was thrown other with the `jwt` guard example in the docs.  If I can think of something Ill create a PR - You are right it doesn't make sense as we need to generate the active and refresh tokens as opposed to using a session.
