### ISSUE TITLE
add param to request in tenant not working

### ISSUE THREAD

**Issue by webactor724** [archtechx/tenancy#592]
#### Describe the bug

in tenant with sub domain definition add param to  request not work i also active redis bootstraper

`        Stancl\Tenancy\Bootstrappers\RedisTenancyBootstrapper::class, // Note: phpredis is needed
`

bellow code

`$request->request->add(['variable' => 'value']); //add request
`

`dd($request->variable)`
return null

#### Your setup
 - Laravel version:7
 - stancl/tenancy version: 3.4

**Comment by stancl** [comment]
Please don't open multiple bug reports if you don't say what the *package* does wrong and don't fill out the issue template.

If there's a clear thing that the package should be doing and it does something else, you can open a bug report and **fill out expected behavior, actual behavior, and steps to reproduce**.

What you're writing here is really just a support question that one specific thing in a larger codebase doesn't work, without saying how it's related to the package.

**Comment by webactor724** [comment]
ok ..

**Comment by webactor724** [comment]
#Describe the bug
in tenant with sub domain definition add param to request not work

`$request->request->add(['variable' => 'value']); //add request`

dd($request->variable)
return null

#Steps to reproduce
1 - run app in multi database
2- add session driver to SESSION_DRIVER=redis
3- set routes tenant definition to `InitializeTenancyByDomainOrSubdomain::class`
4- active `Stancl\Tenancy\Bootstrappers\RedisTenancyBootstrapper::class` 

#Expected behavior
i need add param to $request in tenant grammatically but return null but this code in traditional laravel project work fine

Your setup
Laravel version:7
stancl/tenancy version: 3.4

**Comment by webactor724** [comment]
help me please
