### ISSUE TITLE
Error on TenancyServiceProvider.php initial setup.

### ISSUE THREAD

**Issue by alexchirolde** [archtechx/tenancy#593]
#### Describe the bug
I have installed the package following the Quick Start guide, and I`m getting this error 
**syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)**
on TenancyServiceProvider.php, line 19, see the line below.

```
18    // By default, no namespace is used to support the callable array syntax.
19    public static string $controllerNamespace = '';
```

I have tried using 'App\Http\Controllers' which is the namespace of my Controllers and same thing happens. There is nothing about this on the doc, I assume is something that should work out of the box but is not working for me.
Best,
Alex

#### Your setup
 - Laravel version: [e.g. 8.2.0]
 - stancl/tenancy version: [e.g. 3.1.0]

**Comment by stancl** [comment]
The error says

> unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

If you Google it and click the first result, you'll see

<img width="209" alt="Screen Shot 2021-01-29 at 18 51 15" src="https://user-images.githubusercontent.com/33033094/106309828-f912ad80-6262-11eb-9945-9877832f7421.png">

**Comment by alexchirolde** [comment]
Thanks @stancl !!!

**Comment by imhasem** [comment]
Hi!

i have an issue

when i run command "php artisan tinker"

I receive below error. can you please help me to fix.

> 

   **ParseError

  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

  at app/Providers/TenancyServiceProvider.php:19
     15▕
     16▕ class TenancyServiceProvider extends ServiceProvider
     17▕ {
     18▕     // By default, no namespace is used to support the callable array syntax.
  ➜  19▕     public static string $controllerNamespace = '';
     20▕
     21▕     public function events()
     22▕     {
     23▕         return [

      +1 vendor frames
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("App\Providers\TenancyServiceProvider")

      +8 vendor frames
  11  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))**

**Comment by stancl** [comment]
Can you read text?

**Comment by webbravo** [comment]
Hello, good day, I had the same problem because I was using Php@8.1, So I solved this Problem simply by stepping down my default PHP version to 7.4, and my machine setup was MacBook Pro running Catalina OS,  

So how did I achieve this? 

-  `php -v` (To see what version PHP has)
-  `brew install php@7.4`
-  `brew unlink php@8.1 && brew link --force php@7.4` _remember its `brew unlink php@{current default version}`_
-  run `echo export PATH="/usr/local/opt/php@7.4/bin:$PATH"`
-  _(Optionally, do a manual edit)_ `vim ~/.zshrc` 
    add to the config file `export PATH="/usr/local/opt/php@7.4/bin:$PATH"`
-  source ~/.zshrc
- `php -v` to check if switching was successful.

Good luck.
