### ISSUE TITLE
Laravel config caching issue with  \Stancl\Tenancy\Features\TenantConfig

### ISSUE THREAD

**Issue by cmcfadden** [archtechx/tenancy#603]
#### Describe the bug
Apologies if this is a misunderstanding - it seems like `artisan config:cache` breaks the  \Stancl\Tenancy\Features\TenantConfig config mapping feature, because the cache doesn't actually set the static $storageToConfigMap array within TenantConfig. 

#### Steps to reproduce
Config config mapping for tenants
Call `artisan config:cache`
Attempt to use mapped config values via config()
-> null values

#### Expected behavior
Config values as loaded from the tenant database entry

#### Your setup
 - Laravel version: [e.g. ^8.0]
 - stancl/tenancy version: [e.g. ^3.2]

**Comment by stancl** [comment]
I don't think it should break anything, can you give example code that I can paste into an empty project to reproduce this?

Config caching only caches dynamic calls inside config files afaik. Runtime changes to config should still work

**Comment by cmcfadden** [comment]
Sure, I'll pull together a sample. The issue I was seeing was because of this structure:
```
\Stancl\Tenancy\Features\TenantConfig::$storageToConfigMap = [
        'sample_config_value' => 'app.sample_config_value',
],
```

When `config:cache` is called, it tries to set that value statically, which doesn't have any lasting impact. Then at runtime, when Tenancy goes to loop through that array in the `TenantConfig.php` class, it's empty because the config hasn't been loaded.

**Comment by cmcfadden** [comment]
My bad - I'd misread the docs. I was setting the storageToConfigMap from inside the tenancy.php config file. Moving it to the `TenancyServiceProvider` solved it.

**Comment by genesiscz** [comment]
Related to this config caching issue — the broader problem is that `CacheManager` is registered as a singleton at boot and stays active permanently. `CacheTenancyBootstrapper` only controls which tenant the tags belong to, but the tagging logic itself always runs.

This means any `Cache::` or `cache()` call in contexts without a tenant (queue workers, console commands, error handlers, Telescope listeners) crashes with `Call to a member function getTenantKey() on null` — see #870 for the same stack trace reported by multiple users.

We worked around it with `app('cache.store')` for non-tenant-scoped cache access, but the package should handle null tenant gracefully in `CacheManager` rather than crashing.

**Comment by stancl** [comment]
@genesiscz I do not see how this is related to the issue at hand?

As far as any legitimate issues in this specific thread are concerned, TenantConfig was changed to a bootstrapper which has better lifecycle mechanics in v4 so all these past discussions are moot.
