### ISSUE TITLE
$currentDomain is null when using cached lookup

### ISSUE THREAD

**Issue by ralfinsh** [archtechx/tenancy#632]
#### Describe the bug
When using cached tenant lookup with subdomain identification, the `DomainTenantResolver::$currentDomain` always is `null` for cached lookups.

#### Steps to reproduce
1) Install `stancl/tenancy`
2) Create one tenant and its subdomain
3) Use subdomain identification
4) Enable cached lookup (set `DomainTenantResolver::$shouldCache = true;`)
5) Create Route, which displays `DomainTenantResolver::$currentDomain`
In ***`routes/tenant.php`***
```php
Route::get('/test', function () {
    dd(\Stancl\Tenancy\Resolvers\DomainTenantResolver::$currentDomain);
});
```
6) Access the route at least **twice**.
6.1. it displays Domain model (because it caches tenant on first call)
6.2. from now on it displays `null`

#### Expected behavior
Every time accessing this route (getting `DomainTenantResolver::$currentDomain`), you should get current domain instance.

##### Possible solution?
In ***`CachedTenantResolver.php`***
```php
  // define domain property
  public static $currentDomain;

  // update resolve method
  public function resolve(...$args): Tenant
  {
      // rest of the code...

      //  (line 39) the problem - currently the current domain is not set when using cached lookup
      if ($this->cache->has($key)) {
          $tenant = $this->cache->get($key);
          // I guess, it could be done like that, because it caches only one domain per key
          static::$currentDomain = $tenant->domains->first();
          return $tenant;
      }

      // rest of the code...
  }
```

#### Your setup
 - Laravel version: 8.36.0
 - stancl/tenancy version: 3.4.2
 - Cache driver: redis

**Comment by stancl** [comment]
Hey, thanks for reporting this.

We definitely can't add `$currentDomain` in `CachedTenantResolver`, because there are multiple resolvers, some of which don't use domains at all. Also, `domains->first()` defeats the purpose of `$currentDomain`; if tenants could only have one domain, there'd be no need to set the current domain as a static property, and you could just get the tenants one domain.

The point of the property is to say _which_ domain is the current one.

We could add a method call here:

https://github.com/stancl/tenancy/blob/27e9fb4a692a15ca2fd320799d97fc657cb14b68/src/Resolvers/Contracts/CachedTenantResolver.php#L39-L41

Right before the return, it could do something like:

```php
$tenant = $this->cache->get($key);

if (method_exists($this, 'identified')) {
    $this->identified($tenant, ...$args);
}

return $tenant;
```

And `DomainTenantResolver` would have:

```php
public function identified(Tenant $tenant, ...$args)
{
    $domain = $this->getDomain($args[0]);
}

public function getDomain($domain): Domain
{
    return config('tenancy.domain_model')::where('domain', $domain)->first();
}
```

And this line:

https://github.com/stancl/tenancy/blob/27e9fb4a692a15ca2fd320799d97fc657cb14b68/src/Resolvers/DomainTenantResolver.php#L32

Could be replaced by the `getDomain()` call as well, since we just moved the logic there.

Feel free to send a PR. Can't say I'd merge the exact implementation I described here, but this is roughly how it should be structured.
