### ISSUE TITLE
Clearing a cache tag, clears ALL cache!

### ISSUE THREAD

**Issue by tamkeen-tms** [archtechx/tenancy#645]
#### Describe the bug
Consider the following code:
```php
// Tag-less key
cache()->put('key1', 'value1');
// Tagged key
cache()->tags('tag1')->put('key2', 'value2');
```
Now delete keys under "tag1"
```php
cache()->tags('tag1')->clear();
```
In the above example not only the "key2" will be deleted, but also "key1"! The whole cache in fact will be cleared!

This library handles multi-tenancy caching by adding all the tenant's cache keys under a tenant tag (e.g. tenant_xyz). And the  CacheManager passes all calls through ->tags([ tenant tag ]) first, to assure that get/put/delete/... only works on the current tenant. 

That means that if try to clear keys under a certain other tag, the library will add the tenant's tag to the tags array (previously hold only the user's tag), and Laravel's beheiver is to clear all keys under EITHER tags ([here](https://laravel.com/docs/5.7/cache#removing-tagged-cache-items))! And in this case, ALL the tenant's cache will be deleted, since it's all under the tenant's tag.

#### Steps to reproduce
Simply use the code above and try to dd the value of key1

#### Expected behavior
Only the tag's keys should be deleted

#### Your setup
 - Laravel version: [e.g. 7.5.0]
 - stancl/tenancy version: [e.g. 3.1.0]

**Comment by stancl** [comment]
Hey, thanks for the report. Seems like the tags approach isn't ideal, even if it seemed nice due to how easy deleting individual tenants' cache is by specifying the tags.

I'll change this in v4 probably by making the cache use prefixes instead of tags, and I'll add a custom command for clearing tenant cache.

**Comment by tamkeen-tms** [comment]
Great. I think prefixed keys is the way to go too> A quick fix also could be to exclude the "clear" method from that rule in the CacheManager, thus allowing clearing only the passed tags, not the tenant's primary tag.

Also If you manage to find time for one more extra thing in this area I believe it should be something to handle cache in the centeral app scope. Because currently everything is linked to the tenants, but what if one wanted to cache something shared between all tenants?

Thanks for the time and effort.

**Comment by stancl** [comment]
> but what if one wanted to cache something shared between all tenants

You can use the `CentralCache` facade or the `central_cache()` helper iirc. It's possible that I didn't document them, but I think they should be mentioned somewhere.

**Comment by stancl** [comment]
Sorry, global cache, not central.

**Comment by dpslwk** [comment]
Even in a bare laravel app with Redis cache
```
cache()->tags('tag1')->clear();
```
will clear all the cache not just the tags

it should in fact be `flush()` to just clear the keys under the tags
```
cache()->tags('tag1')->flush();
```

however 
https://laravel.com/docs/8.x/cache#removing-tagged-cache-items

with a tenant say `foo` this `cache()->tags('tag1')->flush();` is basically the same as `cache()->tags(['tenantfoo', 'tag1'])->flush();`
and so both tags are cleared, its treated more as an `or` than an `and`
if you had put something under 'tag1' in central\global even that would be cleared

Since I'm looking to use tags in my tenant best solution I have rite now is it disable `CacheTenancyBootstrapper` and use `RedisTenancyBootstrapper` for the `cache` connection

**Comment by ahmed-esmail-1** [comment]
Hello everyone, I have used multi db and everything, but how to implement the cache ?
Because normal cache is not working

and I couldn't get what you mean by this :-
cache
The CacheManager instance that's resolved when you use the Cache or the cache() helper will be replaced by Stancl\Tenancy\CacheManager. This class automatically uses [tags](https://laravel.com/docs/master/cache#cache-tags). The tag will look like config('tenancy.cache.tag_base') . $uuid.

[https://tenancyforlaravel.com/docs/v1/configuration/](url)
