### ISSUE TITLE
Add connection as part of tenant's parameters

### ISSUE THREAD

**Issue by carlos-mora** [archtechx/tenancy#92]
Allow the user to choose the connection on a per tenant basis allows to do advanced SaaS configuration, like multiple data servers, migration of tenants from one server to another, etc.
'Connection' parameter can be added to the create() method. Deafult to 'tenancy' will keep backward compatibility.

**Comment by stancl** [comment]
> 'Connection' parameter can be added to the create() method

I won't add a parameter for this so that this can be configured later, as the client grows, and due to the fact that I've already added a feature letting you set tenant data on `create()`.

I will add two features that will let developers implement this.

1. Set a key name (similarly to [`database_name_key`](https://github.com/stancl/tenancy/pull/86/files#diff-e6932ae96925382849a4727302b201d8R46) for an array that will be merged with the running `config()` on tenant init. 
      ```php
      tenant()->put('_global_config', ['database.connection' => 'foo'], $uuid); 
      tenant()->init($domain); // sets database.connection to foo
      ```
2. Add a `bootstrapping()` (and `bootstrapped()`?) method that would let hook into the tenancy bootstrapping process.
    ```php
    Tenancy::bootstrapping(function ($tenancy) {
        if ($tenancy->tenant['uuid'] === 'foo') {
            config(['database.connection' => 'bar']);
        }
    });
    ```

**Comment by stancl** [comment]
I find the event-based approach cleaner and I don't see much use for the config merging feature when the events feature is added, so I'll go just with the events.
